### ISSUE TITLE
 Issue with Pinchbar Gesture Not Working in Cubase 13 on MacOS M1 Max

### ISSUE THREAD

**Issue by SolBeys** [pnoqable/PinchBar#3]
Hi there,

I recently downloaded Pinchbar to enable horizontal zooming with my trackpad, similar to the functionality in Logic Pro and Ableton Live. However, I'm encountering an issue where the Pinchbar gesture doesn't work in Cubase, despite it showing as active on the touchbar.

Here are the details of my setup:

Operating System: MacOS M1 Max (Version: Sonoma 14.0)

After launching both Pinchbar and Cubase, the Pinchbar gesture doesn't have any effect in Cubase, even though it appears to be functioning properly on the touchbar. But the vertical zoom works with CMD + pinch.

I would greatly appreciate any assistance or guidance on how to resolve this issue. If there are any specific settings or configurations I need to adjust, please let me know. Thank you in advance for your help!

Best regards,

**Comment by pnoqable** [comment]
Hi SolBeys,

yep, this is the current status of compatibility. Cubase 13 seems to handle modifier keys of incoming mouse events differently than before. Have a look at #2.

Closing this as a duplicate
