### ISSUE TITLE
Binary Release of PinchBar 0.3

### ISSUE THREAD

**Issue by pnoqable** [pnoqable/PinchBar#4]
It's getting time for the release of PinchBar 0.3.

As I mentioned in #2 and in [Cubase's User Forum](https://forums.steinberg.net/t/new-solution-continuous-pinch-to-zoom-for-cubase-on-macos/830052/49), properly signed binary releases require an active membership in Apple's developer programm. Having personally invested for signing PinchBar's first releases, I now need to allocate this cost to PinchBar's users.

[By contributing to this request](https://gofund.me/bba95fd5), you effectively accelerate the release of PinchBar 0.3, which will fix compatibility with Cubase 13.

Of Course, contributors will be included in special thanks on PinchBar's front page.

**Comment by Yuli-boop** [comment]
just checking in, was there any movement on this?

**Comment by pnoqable** [comment]
Yepp, costs are now covered. gonna tag and deploy 0.3 on a free evening this week.

**Comment by Yuli-boop** [comment]
so awesome =)

**Comment by pnoqable** [comment]
Done: https://github.com/pnoqable/PinchBar/releases/tag/0.3
